# Generated by Django 5.1.2 on 2024-12-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_request_options_remove_request_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(choices=[('30 mins', '30 mins'), ('1 hr', '1 hr'), ('1 hr 30 mins', '1 hr 30 mins'), ('2 hrs', '2 hrs')], max_length=20),
        ),
    ]
