# Generated by Django 5.1.2 on 2024-12-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_remove_booking_status_booking_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='frequency',
            field=models.CharField(choices=[('One-time', 'One-time'), ('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly'), ('Monthly', 'Monthly')], default='One-time', help_text='How often the request should recur.', max_length=15),
        ),
    ]
