# Generated by Django 5.1.2 on 2024-12-01 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_request_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), '30 min'), (datetime.timedelta(seconds=5400), '1 hour 30 min'), (datetime.timedelta(seconds=7200), '2 hour'), (datetime.timedelta(seconds=9000), '2 hour 30 min'), (datetime.timedelta(seconds=10800), '3 hour')]),
        ),
    ]
