# Generated by Django 5.1.2 on 2024-12-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_alter_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='timeliness',
            field=models.CharField(choices=[('On Time', 'On Time'), ('Delayed', 'Delayed')], default='On Time', help_text='Whether the request is On Time or Delayed.', max_length=10),
        ),
    ]
