# Generated by Django 5.1.2 on 2024-12-10 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_request_timeliness'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='language',
            field=models.CharField(choices=[('N/A', 'N/A'), ('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java'), ('Javascript', 'Javascript'), ('R', 'R'), ('SQL', 'SQL')], default='N/A', help_text='Select language related to request if applicable', max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='booking',
            field=models.ForeignKey(default=None, help_text='The booking related to the request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tutorials.booking'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('Change', 'Change Booking'), ('Cancel', 'Cancel Booking'), ('New Booking', 'New Booking')], default='New Booking', help_text='Type of request (e.g., change or cancel the booking).', max_length=15),
        ),
    ]
