# Generated by Django 5.1.2 on 2024-12-11 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='recipients',
            field=models.ManyToManyField(related_name='received_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
