# Generated by Django 5.1.2 on 2024-12-11 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_remove_inquiry_recipient_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='users',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
